'use strict';
const $=id=>document.getElementById(id);
let projects=[],selected=null,lastResult=null,busy=false,selectionVersion=0;
const pretty=s=>s.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
function node(tag,text,cls){const el=document.createElement(tag);if(text!==undefined)el.textContent=String(text);if(cls)el.className=cls;return el;}
async function api(path,options){const response=await fetch(path,options);const value=await response.json();if(!response.ok)throw new Error(value.error||'Request failed');return value;}
function error(message){$('error').textContent=message;$('error').hidden=!message;}
function menu(){const query=$('search').value.toLowerCase();$('projects').replaceChildren();for(const p of projects){if(!(p.title+' '+p.category).toLowerCase().includes(query))continue;const button=node('button',p.title);button.setAttribute('aria-current',String(selected?.id===p.id));button.disabled=busy;button.onclick=()=>select(p);$('projects').append(button);}}
async function select(p){if(busy)return;selected=p;const version=++selectionVersion;menu();$('title').textContent=p.title;$('description').textContent=p.summary;$('category').textContent=p.category;lastResult=null;$('result').hidden=true;$('empty').hidden=false;$('download').disabled=true;error('');$('status').textContent='Loading example…';try{const data=await api('/api/example/'+p.id);if(version!==selectionVersion)return;$('input').value=JSON.stringify(data,null,2);document.querySelector('[value=replay]').checked=true;$('status').textContent='Example loaded. Ready to run.';$('status').className='status';}catch(e){error(e.message);}}
function render(value){lastResult=value;$('empty').hidden=true;$('result').hidden=false;$('download').disabled=false;$('summary').textContent=value.summary;const answerStatus=$('answer-status');if(value.answer_status==='withheld'){answerStatus.textContent='Answer withheld. Review the finding before using this result.';answerStatus.className='answer-status withheld';answerStatus.hidden=false;}else if(value.answer_status==='calculated'){answerStatus.textContent='Calculated from matching records. Human review is required before action.';answerStatus.className='answer-status calculated';answerStatus.hidden=false;}else{answerStatus.hidden=true;answerStatus.textContent='';answerStatus.className='answer-status';}$('metrics').replaceChildren();for(const [key,v] of Object.entries(value.metrics||{})){const item=node('div',undefined,'metric');item.append(node('span',pretty(key)),node('strong',v===null?'—':typeof v==='object'?JSON.stringify(v):v));$('metrics').append(item);}
 $('findings').replaceChildren();for(const f of value.findings||[]){const item=node('div',undefined,'finding '+(f.severity||'info'));item.append(node('h4',f.title||f.code),node('p',f.detail||''));if(f.evidence_ids?.length)item.append(node('p','Sources: '+f.evidence_ids.join(', ')));$('findings').append(item);}if(!(value.findings||[]).length)$('findings').append(node('p','No exceptions in the checks performed. Review the result before acting.','hint'));
 $('actions').replaceChildren();if(value.actions?.length){$('actions').append(node('h3','Next steps'));for(const a of value.actions){const item=node('div',a.label||pretty(a.action||a.type||'Review action'),'action');item.append(node('small',a.owner?'Owner: '+a.owner:'Human review required'));for(const [key,v] of Object.entries(a)){if(['label','action','type','owner'].includes(key))continue;item.append(node('small',pretty(key)+': '+(typeof v==='object'?JSON.stringify(v):v)));}$('actions').append(item);}}
 $('details').replaceChildren();const standard=new Set(['project','summary','answer_status','metrics','findings','actions','human_review_required','execution']);for(const [key,v] of Object.entries(value)){if(standard.has(key)||v===null)continue;const section=node('section');section.append(node('h3',pretty(key)));if(Array.isArray(v)&&v.length&&v.every(x=>x&&typeof x==='object'&&!Array.isArray(x))){const wrap=node('div',undefined,'table-wrap'),table=node('table'),head=node('tr');const columns=[...new Set(v.flatMap(x=>Object.keys(x)))];for(const col of columns)head.append(node('th',pretty(col)));const thead=node('thead');thead.append(head);table.append(thead);const tbody=node('tbody');for(const row of v){const tr=node('tr');for(const col of columns){const td=node('td');if(typeof row[col]==='object')td.append(node('pre',JSON.stringify(row[col],null,2)));else td.textContent=String(row[col]??'');tr.append(td);}tbody.append(tr);}table.append(tbody);wrap.append(table);section.append(wrap);}else{const details=node('details',undefined,'raw');details.append(node('summary','View '+pretty(key).toLowerCase()),node('pre',typeof v==='string'?v:JSON.stringify(v,null,2)));section.append(details);}$('details').append(section);}
 $('raw').textContent=JSON.stringify(value,null,2);const live=value.execution.mode==='live';$('status').className='status'+(live?' live':'');$('status').textContent=live?'Live AI completed · '+value.execution.calls.length+' model call(s) · Human review required':'Example replay completed · Recorded response, no model call';}
$('search').oninput=menu;$('reload').onclick=()=>selected&&select(selected);
$('upload').onchange=async event=>{const file=event.target.files[0];if(!file)return;try{if(file.size>500000)throw new Error('Choose a JSON file smaller than 500 KB.');const raw=await file.text();JSON.parse(raw);$('input').value=raw;document.querySelector('[value=live]').checked=true;error('');}catch(e){error(e.message);}};
$('run').onclick=async()=>{if(!selected||busy)return;error('');const rawInput=$('input').value;try{JSON.parse(rawInput);}catch{error('Input is not valid JSON. Check commas and quoted field names.');return;}busy=true;menu();$('run').disabled=true;$('reload').disabled=true;$('upload').disabled=true;$('status').textContent='Working through the supplied records…';$('status').className='status busy';$('result').hidden=true;$('empty').hidden=true;$('download').disabled=true;lastResult=null;try{render(await api('/api/run',{method:'POST',headers:{'Content-Type':'application/json','X-Workspace-Token':document.querySelector('meta[name=workspace-token]').content},body:'{"project":'+JSON.stringify(selected.id)+',"mode":'+JSON.stringify(document.querySelector('[name=mode]:checked').value)+',"input":'+rawInput+'}'}));}catch(e){error(e.message);$('status').textContent='Run failed. No result produced.';$('status').className='status';}finally{busy=false;$('run').disabled=false;$('reload').disabled=false;$('upload').disabled=false;menu();}};
$('download').onclick=()=>{if(!lastResult)return;const url=URL.createObjectURL(new Blob([JSON.stringify(lastResult,null,2)],{type:'application/json'}));const a=node('a');a.href=url;a.download=selected.id+'-result.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
api('/api/projects').then(data=>{projects=data;menu();if(projects.length)select(projects[0]);}).catch(e=>error(e.message));
